# Generated by Django 3.1.7 on 2021-04-12 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_remove_feedback_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='image',
        ),
        migrations.AddField(
            model_name='feedback',
            name='product_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='problem_issue',
            field=models.TextField(default='', max_length=256),
        ),
    ]
