# Generated by Django 3.1.7 on 2021-04-22 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_feedback_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='image',
        ),
    ]
