# Generated by Django 3.1.7 on 2021-04-22 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_remove_feedback_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='feedback_image',
            field=models.ImageField(default='no_img.png', upload_to='feedback_images'),
        ),
    ]
