# Generated by Django 3.1.7 on 2021-04-29 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_auto_20210422_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='product_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product'),
        ),
    ]
